In [2]:
import pandas as pd
import seaborn as sns
df = sns.load_dataset("titanic")
type(df)

pandas.core.frame.DataFrame

In [3]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [14]:
df.to_csv("titanic.csv", index = False) # copy dataset

In [19]:
import numpy as np
np.set_printoptions(suppress=True)
df.iloc[0:3]

np.float64(22.0)

In [41]:
x = len(df.columns)

In [56]:
df.loc[890]

survived                0
pclass                  3
sex                  male
age                  32.0
sibsp                   0
parch                   0
fare                 7.75
embarked                Q
class               Third
who                   man
adult_male           True
deck                  NaN
embark_town    Queenstown
alive                  no
alone                True
Name: 890, dtype: object

In [57]:
len(df)

891

In [67]:
# mask = (df['age'] > 30).values
df.iloc[(df['age'] > 30).values,:]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [71]:
df[df['age'] > 30][['age', 'fare']]

      age     fare
1    38.0  71.2833
3    35.0  53.1000
4    35.0   8.0500
6    54.0  51.8625
11   58.0  26.5500
..    ...      ...
873  47.0   9.0000
879  56.0  83.1583
881  33.0   7.8958
885  39.0  29.1250
890  32.0   7.7500

[305 rows x 2 columns]

In [72]:
df.loc[(df['age'] > 30) & (df['pclass'] == 3), ['age', 'sex', 'pclass']]

      age     sex  pclass
4    35.0    male       3
13   39.0    male       3
18   31.0  female       3
25   38.0  female       3
40   40.0  female       3
..    ...     ...     ...
860  41.0    male       3
873  47.0    male       3
881  33.0    male       3
885  39.0  female       3
890  32.0    male       3

[103 rows x 3 columns]

In [75]:
df.loc[(df['age']>30) & (df['fare']<9), ['age','fare']]

      age    fare
4    35.0  8.0500
94   59.0  7.2500
103  33.0  8.6542
104  37.0  7.9250
108  38.0  7.8958
..    ...     ...
847  35.0  7.8958
851  74.0  7.7750
872  33.0  5.0000
881  33.0  7.8958
890  32.0  7.7500

[72 rows x 2 columns]

In [81]:
df.age.isna().sum()

np.int64(177)

In [82]:
mask = df['fare'] > df['fare'].mean()
df[mask]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,1,1,female,45.0,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
867,0,1,male,31.0,0,0,50.4958,S,First,man,True,A,Southampton,no,True
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False

In [83]:
df.loc[df['age']>30, ['age','fare']]

      age     fare
1    38.0  71.2833
3    35.0  53.1000
4    35.0   8.0500
6    54.0  51.8625
11   58.0  26.5500
..    ...      ...
873  47.0   9.0000
879  56.0  83.1583
881  33.0   7.8958
885  39.0  29.1250
890  32.0   7.7500

[305 rows x 2 columns]

In [85]:
df.iloc[:100, -2:]

   alive  alone
0     no  False
1    yes  False
2    yes   True
3    yes  False
4     no   True
..   ...    ...
95    no   True
96    no   True
97   yes  False
98   yes  False
99    no  False

[100 rows x 2 columns]

In [88]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression

Libraries imported successfully

In [93]:
import seaborn as sns

df_raw = sns.load_dataset("titanic")

df = df_raw.copy()

In [98]:
print(id(df_raw))
print(id(df))

5854845696
5854847824

In [99]:
df.describe(include = 'object')

         sex embarked  who  embark_town alive
count    891      889  891          889   891
unique     2        3    3            3     2
top     male        S  man  Southampton    no
freq     577      644  537          644   549

In [103]:
pd.crosstab(df['who'], df['sex'])

sex    female  male
who
child      43    40
man         0   537
woman     271     0

In [107]:
df['deck'].value_counts(dropna=False)

deck
NaN    688
C       59
B       47
D       33
E       32
A       15
F       13
G        4
Name: count, dtype: int64

In [115]:
pd.crosstab(df['class'], df['deck'].cat.add_categories("Missing").fillna("Missing"))

deck     A   B   C   D   E  F  G  Missing
class
First   15  47  59  29  25  0  0       41
Second   0   0   0   4   4  8  0      168
Third    0   0   0   0   3  5  4      479

In [120]:
df[df.embarked.isna()]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
61,1,1,female,38.0,0,0,80.0,NaN,First,woman,False,B,NaN,yes,True
829,1,1,female,62.0,0,0,80.0,NaN,First,woman,False,B,NaN,yes,True

In [122]:
df.embark_town.value_counts()

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

In [123]:
df.age.median()

28.0

In [126]:
df.fillna({df.age: df.age.median()}, inplace = True)

TypeError: unhashable type: 'Series'

In [127]:
df['age'].fillna(df['age'].median(), inplace = True)

/var/folders/r2/t2lb1vw12x16gf57gwdc6qth0000gn/T/ipykernel_70460/2184317208.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(), inplace = True)

In [129]:
df_raw.age.isna().sum()

np.int64(177)

In [142]:
df = df_raw.copy()

In [131]:
df.age.isna().sum()

np.int64(177)

In [135]:
df.fillna({'age': df.age.median()}, inplace=True)

In [136]:
df.age.isna().sum()

np.int64(0)

In [137]:
df.drop(columns=['deck'], inplace = True)

In [143]:
df = df.drop(columns=['deck'])

In [148]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='object')

In [163]:
df.groupby(['who', 'sex'])['survived'].agg(
    avg='mean', 
    sum_survived='sum', 
    cnt_all='count'
)

                   avg  sum_survived  cnt_all
who   sex
child female  0.651163            28       43
      male    0.525000            21       40
man   male    0.163873            88      537
woman female  0.756458           205      271

In [161]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='object')

In [164]:
data = pd.get_dummies(df, columns = ['sex', 'embarked'], drop_first = True)

In [168]:
pd.crosstab(data['sex_male'], data['adult_male'])

adult_male  False  True
sex_male
False         314      0
True           40    537

In [169]:
data['sex_male'].value_counts()

sex_male
True     577
False    314
Name: count, dtype: int64

In [170]:
data['adult_male'].value_counts()

adult_male
True     537
False    354
Name: count, dtype: int64

In [171]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# Sample data
df = pd.DataFrame({'color': ['red', 'blue', 'green', 'red']})

# Initialize and transform
encoder = OneHotEncoder(sparse_output=False)
encoded_data = encoder.fit_transform(df[['color']])

# Get feature names for the new columns
column_names = encoder.get_feature_names_out(['color'])
encoded_df = pd.DataFrame(encoded_data, columns=column_names)

In [172]:
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0

In [176]:
pwd

'/Users/apple/LogicMojo-AI-ML-March26-makarand'